### ISSUE TITLE
InaccessibleObjectException on Java 17

### ISSUE THREAD

**Issue by anatoliykmetyuk** [Philippus/sbt-dotenv#192]
Getting the following when using the plugin with Scala 3 on Java 17; works fine on Java 8:

```
[info] .env detected (fileName=.env). About to configure JVM System Environment with new map
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.HashMap java.lang.ProcessEnvironment.theEnvironment accessible: module java.base does not "opens java.lang" to unnamed module @a89dec0
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at au.com.onegeek.sbtdotenv.DirtyEnvironmentHack$.$anonfun$setEnv$1(DirtyEnvironmentHack.scala:44)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at au.com.onegeek.sbtdotenv.DirtyEnvironmentHack$.setEnv(DirtyEnvironmentHack.scala:38)
        at au.com.onegeek.sbtdotenv.SbtDotenv$.applyEnvironment(SbtDotenv.scala:106)
        at au.com.onegeek.sbtdotenv.SbtDotenv$.$anonfun$configureEnvironment$2(SbtDotenv.scala:79)
        at scala.Option.fold(Option.scala:251)
        at au.com.onegeek.sbtdotenv.SbtDotenv$.configureEnvironment(SbtDotenv.scala:79)
        at au.com.onegeek.sbtdotenv.SbtDotenv$autoImport$.$anonfun$dotEnv$1(SbtDotenv.scala:44)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.Project$.setProject(Project.scala:502)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:979)
        at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:917)
        at sbt.Command$.$anonfun$applyEffect$4(Command.scala:151)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:146)
        at sbt.Command$.process(Command.scala:190)
        at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:246)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:246)
        at sbt.MainLoop$.processCommand(MainLoop.scala:279)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:164)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:290)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:326)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:164)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
        at sbt.MainLoop$.next(MainLoop.scala:164)
        at sbt.MainLoop$.run(MainLoop.scala:145)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:120)
        at sbt.io.Using.apply(Using.scala:28)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:113)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:67)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:52)
        at sbt.MainLoop$.runLogged(MainLoop.scala:43)
        at sbt.StandardMain$.runManaged(Main.scala:225)
        at sbt.xMain$.$anonfun$run$11(Main.scala:135)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:610)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:390)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:600)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:600)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:390)
        at sbt.xMain$.withStreams$1(Main.scala:88)
        at sbt.xMain$.run(Main.scala:123)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
        at sbt.xMain.run(Main.scala:47)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[info] Configured .env environment
```

**Comment by Philippus** [comment]
https://github.com/Philippus/sbt-dotenv#illegal-reflective-access-warnings-and-exceptions
